-- Add missing land columns to units table
ALTER TABLE units ADD COLUMN IF NOT EXISTS ada TEXT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS parsel TEXT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS density NUMERIC;
ALTER TABLE units ADD COLUMN IF NOT EXISTS height_limit NUMERIC;
ALTER TABLE units ADD COLUMN IF NOT EXISTS district TEXT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS area NUMERIC;
ALTER TABLE units ADD COLUMN IF NOT EXISTS living_rooms INTEGER;
ALTER TABLE units ADD COLUMN IF NOT EXISTS floor INTEGER;
ALTER TABLE units ADD COLUMN IF NOT EXISTS total_floors INTEGER;
ALTER TABLE units ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE units ADD COLUMN IF NOT EXISTS price_sale NUMERIC;
ALTER TABLE units ADD COLUMN IF NOT EXISTS price_month NUMERIC;
ALTER TABLE units ADD COLUMN IF NOT EXISTS price_day NUMERIC;
